---
# MIT License

# Copyright (c) 2018 

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# tasks file for openldap
- name: Install remotelly debconf
  apt: 
    update_cache: yes
    name: debconf 
    install_recommends: yes
    state: present

- name: Configure ldap properties
  debconf:
    name: slapd
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
    question: "{{ item.question }}"
  loop:
    - question: slapd/no_configuration
      vtype: boolean
      value: false
    - question: slapd/dump_database
      vtype: select
      value: when needed
    - question: slapd/dump_database_destdir
      vtype: string
      value: /var/backups/slapd-VERSION
    - question: slapd/move_old_database
      vtype: boolean
      value: false
    - question: slapd/invalid_config
      vtype: boolean
      value: true
    - question: slapd/domain
      vtype: string
      value: "{{ ldap_organization_domain }}"
    - question: shared/organization
      vtype: string
      value: "{{ ldap_organization_name }}"
    - question: slapd/password1
      vtype: password
      value: "{{ ldap_admin_pw }}"
    - question: slapd/password2
      vtype: password
      value: "{{ ldap_admin_pw }}"
    - question: slapd/password_mismatch
      vtype: note
      value: ""
    - question: slapd/purge_database
      vtype: boolean
      value: false
    - question: slapd/internal/adminpw
      vtype: password
      value: "{{ ldap_admin_pw }}"
    - question: slapd/internal/generated_adminpw
      vtype: password
      value: "{{ ldap_admin_pw }}"
    - question: slapd/upgrade_slapcat_failure
      vtype: error
      value: ""
    - question: slapd/backend
      vtype: select
      value: MDB
    - question: slapd/unsafe_selfwrite_acl
      vtype: note
      value: ""
    - question: slapd/ppolicy_schema_needs_update
      vtype: select
      value: abort installation

- name: Install ldap server
  apt:
    name: ["slapd", "ldap-utils", "python-ldap"]
    state: present

- name: Create directories to store certificates and keys
  file:
    path: "{{ item }}"
    group: "openldap"
    state: "directory"
    mode: "750"
    owner: "openldap"
  loop:
    - "{{ files_dir }}"
    - "{{ CA.ca_cert_file | dirname }}"
    - "{{ CA.clients[0].client_cert_file | dirname }}"

- name: copy neccesary certificates and keys (I)
  copy:
    dest: "{{ item }}"
    src: "{{ item }}"
    mode: "644"
    owner: "openldap"
    group: "openldap"
  loop:
    - "{{ CA.ca_cert_file }}"

- name: copy neccesary certificates and keys (II)
  copy:
    dest: "{{ item }}"
    src: "{{ item }}"
    mode: "640"
    owner: "openldap"
    group: "openldap"
  loop:
    - "{{ CA.clients[0].client_cert_file }}"
    - "{{ CA.clients[0].client_priv_key }}"

- name: Configure OpenLDAP SSL support (1)
  file: 
    path: "{{ files_dir }}"
    owner: openldap
    group: openldap


# https://docs.ansible.com/ansible/latest/collections/community/general/ldap_attrs_module.html
# Enable it by installying:
#    ansible-galaxy collection install community.general
# 

- name: Configure OpenLDAP SSL support
  community.general.ldap_attrs:
    dn: "cn=config"
    attributes:
       olcTLSCertificateFile: "{{ CA.clients[0].client_cert_file }}"
       olcTLSCertificateKeyFile: "{{ CA.clients[0].client_priv_key }}"
       olcTLSCACertificateFile: "{{ CA.ca_cert_file }}"
    state: exact


- name: Enable SSL service on LDAP
  lineinfile:
    path: /etc/default/slapd
    regexp: '^SLAPD_SERVICES='
    line: SLAPD_SERVICES="ldap:/// ldapi:/// ldaps:///"

- name: Restart slapd service (OpenLDAP)
  service:
    name: slapd
    state: restarted

- name: Configure ldap client
  lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ ansible_default_ipv4.address }} {{ ldap_server_domain }}"

- name: Configure ldap client
  lineinfile:
    path: /etc/ldap/ldap.conf
    state: present
    line: "{{ item }}"
  loop:
    - "TLS_CACERT {{ CA.ca_cert_file }}"
    - "TLS_REQ_CERT never"
    - "BASE {{ ldap_base_dn }}"
    - "URI ldaps://{{ ldap_server_domain }}"
