---

ldap_server_domain: "ldap.esei.uvigo.es"
ldap_organization_domain: "esei.uvigo.es"
ldap_organization_name: "ESEI"
ldap_admin_pw: "test"
files_dir: "/opt/ssl/"
CA: 
  ca_cn: "{{ ldap_organization_domain }}"
  ca_cert_file: "{{ files_dir }}/ca/ca.pem"
  ca_csr_file: "{{ files_dir }}/ca/ca.csr"
  ca_priv_key: "{{ files_dir }}/ca/ca.key"
  clients:
    - client_cn: "{{ ldap_server_domain }}"
      client_cert_file: "{{ files_dir }}/ldap/ldap.pem"
      client_csr_file: "{{ files_dir }}/ldap/ldap.csr"
      client_priv_key: "{{ files_dir }}/ldap/ldap.key"