---

- hosts: localhost
  gather_facts: yes
  vars:
    ldap_organization_domain: "esei.uvigo.es"
    ldap_base_dn: "{{ ldap_organization_domain | replace('.', ',dc=') | regex_replace('^', 'dc=')  }}"
  tasks:
     - name: Debug
       debug:
         msg: "{{ ldap_base_dn }}"


     - name: Debug
       debug:
         msg: "{{ hostvars['ldap_server'].ansible_ssh_host }}"