---
# tasks file for ldap-client

- name: Install client software
  apt:
    name: ["ldap-utils", "jxplorer", "x11-xserver-utils"]
    state: present

- name: Configure this host as ldap client
  lineinfile:
      path: /etc/hosts
      state: present
      line: "{{ ldap_server_ip }} {{ ldap_server_domain }}"

- name: Configure ldap client
  lineinfile:
      path: /etc/ldap/ldap.conf
      state: present
      line: "{{ item }}"
  loop:
  - "TLS_CACERT {{ CA.ca_cert_file }}"
  - "TLS_REQ_CERT never"
  - "BASE {{ ldap_base_dn }}"
  - "URI ldaps://{{ ldap_server_domain }}"

- name: Import SSL certificate from our CA to Java cacerts keystore
  java_cert:
    cert_path: "{{ CA.ca_cert_file }}"
    keystore_path: /etc/ssl/certs/java/cacerts #default on Debian
    keystore_pass: changeit
    cert_alias: "{{ ldap_organization_name }}"
    state: absent

- name: Import SSL certificate from our CA to Java cacerts keystore
  java_cert:
    cert_path: "{{ CA.ca_cert_file }}"
    keystore_path: /etc/ssl/certs/java/cacerts #default on Debian
    keystore_pass: changeit
    cert_alias: "{{ ldap_organization_name }}"
    state: present

- name: Inform
  debug:
    msg: "Just start \"ssh -X -Y username@hostname jxplorer\" to run it"