---
# tasks file for ldap-client

- name: Install client software
  ansible.builtin.apt:
    update_cache: true
    name: ["ldap-utils", "jxplorer", "x11-xserver-utils"]
    state: present

- name: Create directories to store certificates and keys
  ansible.builtin.file:
    path: "{{ item }}"
    group: "root"
    state: "directory"
    mode: "755"
    owner: "root"
  loop:
    - "{{ files_dir }}"
    - "{{ CA.ca_cert_file | dirname }}"

- name: copy neccesary certificates and keys
  ansible.builtin.copy:
    dest: "{{ item }}"
    src: "{{ item }}"
    mode: "644"
    owner: "root"
    group: "root"
  loop:
    - "{{ CA.ca_cert_file }}"

- name: Configure this host as ldap client
  ansible.builtin.lineinfile:
      path: /etc/hosts
      state: present
      line: "{{ ldap_server_ip }} {{ ldap_server_domain }}"

- name: Configure ldap client
  ansible.builtin.lineinfile:
      path: /etc/ldap/ldap.conf
      state: present
      line: "{{ item }}"
  loop:
  - "TLS_CACERT {{ CA.ca_cert_file }}"
  - "TLS_REQ_CERT never"
  - "BASE {{ ldap_base_dn }}"
  - "URI ldaps://{{ ldap_server_domain }}"

- name: Import SSL certificate from our CA to Java cacerts keystore
  community.general.java_cert:
    cert_path: "{{ CA.ca_cert_file }}"
    keystore_path: /etc/ssl/certs/java/cacerts #default on Debian
    keystore_pass: changeit
    cert_alias: "{{ ldap_organization_name }}"
    state: absent

- name: Import SSL certificate from our CA to Java cacerts keystore
  community.general.java_cert:
    cert_path: "{{ CA.ca_cert_file }}"
    keystore_path: /etc/ssl/certs/java/cacerts #default on Debian
    keystore_pass: changeit
    cert_alias: "{{ ldap_organization_name }}"
    state: present

- name: Inform
  ansible.builtin.debug:
    msg: |
      Just start \"ssh -X -Y username@hostname jxplorer\" to run it.
      certificate problems can be detected using the following command
        openssl s_client -connect {{ ldap_server_domain }}:636 -showcerts
