---
# MIT License

# Copyright (c) 2018 

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# tasks file for CA

- name: Install required software (Debian | Ubuntu)
  ansible.builtin.apt: 
    name: python3-openssl 
    state: present
    update_cache: yes
  when: ansible_distribution=="Debian" or ansible_distribution=="Ubuntu"

- name: Install required software (OSX)
  ansible.builtin.pip: 
    name: pyOpenSSL
    state: present
  when: ansible_distribution=="MacOSX"

- name: Generate a private key for CA
  community.crypto.openssl_privatekey:
    path: "{{ CA.ca_priv_key }}"

- name: Generate a Certificate request 
  community.crypto.openssl_csr:
    path: "{{ CA.ca_csr_file }}"
    privatekey_path: "{{ CA.ca_priv_key }}"
    common_name: "{{ CA.ca_cn }}"
    basic_constraints: 
      - CA:TRUE
      - pathlen:1
    key_usage:
      - keyCertSign
      - cRLSign
      - digitalSignature

- name: Generate the certificates
  community.crypto.x509_certificate:
    path: "{{ CA.ca_cert_file }}"
    privatekey_path: "{{ CA.ca_priv_key }}"
    csr_path: "{{ CA.ca_csr_file }}"
    key_usage:
      - keyCertSign
      - cRLSign
    provider: selfsigned

- name: Generate clients
  ansible.builtin.include_tasks: client.yml
  loop: "{{ CA.clients }}"
  vars:
    client_cn: "{{ item.client_cn }}"
    client_cert_file: "{{ item.client_cert_file }}"
    client_csr_file: "{{ item.client_csr_file }}"
    client_priv_key: "{{ item.client_priv_key }}"

#Fix permissions to ensure certificates can be copied 
#to servers
- name: Change permissions in certificate folders
  ansible.builtin.file: 
    path: "{{ item }}"
    mode: "755"
  loop:
    - "{{ files_dir }}"
    - "{{ CA.ca_cert_file | dirname }}"
    - "{{ CA.clients[0].client_cert_file | dirname }}"

- name: Change permissions in certificate folders
  ansible.builtin.file: 
    path: "{{ item }}"
    mode: "644"
  loop:
    - "{{ CA.clients[0].client_priv_key }}"
    - "{{ CA.clients[0].client_cert_file }}"
  
