---
# MIT License

# Copyright (c) 2018 

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# tasks file for smbADserver

#Inspired in https://www.sysadminsdecuba.com/2018/02/pdc-sencillo-con-samba-4-en-debian-9/

- name: Configure hosts for samba populate
  lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ ansible_default_ipv4.address }} pdc.{{ ldap_server_domain }} PDC.{{ ldap_server_domain }} "

- name: Install samba packages
  apt:
    name: ["samba", "winbind", "krb5-user", "krb5-config", "libpam-winbind", "libnss-winbind", "ntp"]
    state: present

#configure NTP
- name: Configure NTP
  lineinfile:
      path: /etc/ntp.conf
      line: "broadcast {{net_bcast_address}}"
      state: present
  notify:
    - restart ntp


- name: Stop and disable Samba daemons
  systemd:
      name: "{{ item }}"
      enabled: false
      state: stopped
  loop:
    - samba-ad-dc.service 
    - smbd.service 
    - nmbd.service 
    - winbind.service

- name: Backup original Samba and Kerberos 5 configuration
  shell: "mv {{ item.file }} {{ item.backup }}"
  args: 
      creates: "{{ item.backup }}"
  loop:
    - file: /etc/krb5.conf
      backup: /etc/krb5.conf.initial
    - file: /etc/samba/smb.conf
      backup:  /etc/samba/smb.conf.initial

- name: Change hostname according samba configuration
  hostname:
    name: "pdc" #Abbreviation for Primary Domain Controller. Should not be equal to realm or netbios donamin name.

- name: Populate smb.conf configuration file for samba
  shell: |
     samba-tool domain provision --use-rfc2307 --realm {{ ldap_organization_domain }} \
     --domain {{ ldap_organization_domain | regex_replace("\..*$", "") }} \
     --server-role dc --dns-backend SAMBA_INTERNAL --adminpass {{ ldap_admin_pw }}
  args:
    creates: /etc/samba/smb.conf

- name: Configure kerberos with the configuration generated by Samba
  file:
      path: /etc/krb5.conf
      src: /var/lib/samba/private/krb5.conf
      state: link

- name: Enable and start Samba daemons
  systemd:
      name: "samba-ad-dc.service"
      enabled: True
      state: started
      masked: False

#Drop if not explicitly required
- name: Disable password restrictions on samba
  shell: "{{ item }}"
  loop:
   - "samba-tool domain passwordsettings set --complexity=off"
   - "samba-tool domain passwordsettings set --min-pwd-length=6"

- name: Improve compatibility with other services
  ini_file:
    path: /etc/samba/smb.conf
    section: global
    option: "\tldap server require strong auth"
    value: "No"

# - name: Improve compatibility with other services
#   lineinfile:
#     path: /etc/samba/smb.conf
#     line: "\tldap server require strong auth = No"
#     insertbefore: "[netlogon]"

- name: Masks on netlogon
  community.general.ini_file:
    path: /etc/samba/smb.conf
    section: netlogon
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - option: "\tcreate mask" 
      value: "0700"
    - option: "\tdirectory mask"
      value: "0644"


# - name: Masks on netlogon
#   lineinfile:
#     path: /etc/samba/smb.conf
#     line: "{{ item }}"
#     insertbefore: "[sysvol]"
#   loop:
#     - "\tcreate mask = 0700"
#     - "\tdirectory mask = 0644"

- name: Masks on sysvol
  community.general.ini_file:
    path: /etc/samba/smb.conf
    section: sysvol
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - option: "\tcreate mask" 
      value: "0700"
    - option: "\tdirectory mask"
      value: "0644"
  notify:
    - restart samba

# - name: Masks on sysvol
#   lineinfile:
#     path: /etc/samba/smb.conf
#     line: "{{ item }}"
#     insertafter: "[sysvol]"
#   loop:
#     - "\tcreate mask = 0700"
#     - "\tdirectory mask = 0644"
#   notify:
#     - restart samba

- name: Output the info
  debug: 
    msg: |
      Please note that the public key of the CA is in /var/lib/samba/private/tls/ca.pem
      this file is absolutelly necesary to access internal ldap server of samba. 
      In order to connect with a client to the internal ldapserver of samba, you should 
      use the follwoing configuration:
        host: PDC.{{ ldap_server_domain }}
        base_dn: {{ ldap_base_dn }}
        port: 636
        user: cn=Administrator,cn=Users,{{ ldap_organization_domain }}
        password: {{ ldap_admin_pw }}

      If you want to use standard command-line ldap tools (ldapsearch, ldapmodify...)
      you should include the following in your /etc/ldap config file:
        TLS_CACERT	<path where you copied /var/lib/samba/private/tls/ca.pem>
        TLS_REQCERT never
      Please note that the best form to autenticate linux users with samba4 is using 
      winbind pam module (not pam_ldap).
      Please read https://www.sysadminsdecuba.com/2018/02/pdc-sencillo-con-samba-4-en-debian-9/
      to know how to create users, domain workstations, etc.
      
